### ISSUE TITLE
Location Markers - Design [Need Design Input]

### ISSUE THREAD

**Issue by jasonkalmeida** [techforwarren/eventmap#4]
Would love anyone with some design talent to potentially look into designing marker designs for the locations on the map.

For reference, this is the library I'm using for the map/markers, so feel free to look at the documentation for guidance on specific design specs: https://leafletjs.com/examples/custom-icons/

**Comment by danielnarey** [comment]
This is something I could work on. I’m wondering if events fall into distinct categories where it would make sense to have different markers to represent them. Any insight on this?

**Comment by jasonkalmeida** [comment]
Hey @danielnarey! Thanks for dropping by, hahaha.

So I think for now there are just two versions of a single marker we need:
- A general marker for the items on the map (this could be as simple as just a Warren-color-themed version of the default Leaflet markers, but your choice I'm no designer)
- A highlighted version of the general marker - this will be used by the application to identify a single location when a user has selected it through various features of the app

Long term we might want distinct marker categories - for Senator Warren events, call banks, etc, etc - but I think for now we can start with the above. Pretty much all markers we would ever make would require the two variations described above.

Would love to hear your ideas/let me know if you have any questions!

**Comment by danielnarey** [comment]
@jasonkalmeida - I used the source file for the default Leaflet marker as a starting point, and I created a custom Warren marker with a highlighted version. The pixels sizes of the PNGs correspond to what I found in Leaflet’s `dist/images` directory. Because the custom icon has the same dimensions as the default icon, there was no need to create a custom shadow image. Icons will need to be tested live to see how they stand out in a Leaflet map. Any feedback welcome.

The files are here:
https://github.com/danielnarey/techforwarren/tree/master/map-marker

**Comment by jasonkalmeida** [comment]
@danielnarey - oh wow, these look really cool! I'll load them up onto the app tomorrow (Sunday) and share how they look here and provide any feedback I can think of!

**Comment by jasonkalmeida** [comment]
Hey @danielnarey - Here are some screenshots of your markers in the app!

![Screen Shot](https://user-images.githubusercontent.com/5836378/64083671-26f36b80-ccd8-11e9-894e-38fe87a5a1e1.png)

![screenshot](https://user-images.githubusercontent.com/5836378/64083686-4ee2cf00-ccd8-11e9-9e0b-51d7fb0c6265.jpg)

So while I love the design on itself, it personally feels to me that the "Warren Green" of the markers tend to blend in with the colors of the map. Unfortunately our current open source map options generally involve map color codes that involve a similar shade of green for grass-y regions.

I can look into more options, just to confirm there isn't a better option, but I was wondering if the markers could go for a darker color contrast as the primary color? Potentially the Warren purple? I'm no designer, so I'm literally just shooting suggestions in the dark here, they might be terrible 😅

**Comment by danielnarey** [comment]
Yeah, I see what you mean. I’m finding the campaign colors a little hard to work with because if you have too much of the dark blue and red together it looks like a sports team logo, and you also can’t use the red and light green together as foreground and background because it is too intense.

I created two additional versions to test and posted them to the same repo:
https://github.com/danielnarey/techforwarren/tree/master/map-marker

**Comment by jasonkalmeida** [comment]
Hey @danielnarey - sorry for taking so long to get back to you on this.

I love these additional designs! I'm really digging the white one though. Screenshots included below, what do you think?

![blue](https://user-images.githubusercontent.com/5836378/64485431-bf588700-d1d5-11e9-8934-ac95a0c4cb8d.png)

![white](https://user-images.githubusercontent.com/5836378/64485435-c8495880-d1d5-11e9-8585-e4245e6a2471.png)

**Comment by danielnarey** [comment]
@jasonkalmeida - yeah, go with the white background. I think the blue background looks too dark against the map.

**Comment by jasonkalmeida** [comment]
Closing as basic marker has been designed (thanks @danielnarey) and implemented. Future markers/modifications will be raised in new issue.
