### ISSUE TITLE
Search Events by Type

### ISSUE THREAD

**Issue by joegoldbeck** [techforwarren/eventmap#55]

**Comment by chief-dweeb** [comment]
The goal is to allow users to filter events by the kind of event.  

There are two different bits of work: 1) adding the code to do the filtering (client-side) and 2) updating the UI/UX to accommodate another user choice (currently they can only select zipcode and distance range).  Note that I hope to also add a date range, so the UI/UX solution should probably be something that appears and disappears (pop-up, fade-in/out, etc.) so that we have a framework for adding additional searching/filtering options in the future.

**Comment by chief-dweeb** [comment]
I have submitted a pull request (#54) that solves the first issue (client-side filtering) but does not yet adequately solve the second issue (adequate UI/UX).  I am hoping that I can get a code review and comments on both issues - hopefully a thumbs-up on the implementation of client-side filtering and some suggestions on a better solution to the second issue (adequate UI/UX).  -Fred

**Comment by chief-dweeb** [comment]
Pull request (#54) has been merged, so this issue is closed.
