### ISSUE TITLE
Event Time on Event Card

### ISSUE THREAD

**Issue by jasonkalmeida** [techforwarren/eventmap#8]
Functionally, need to figure out how to take Unix timestamp (that is in UTC) and convert it to the event location's timezone and in human-readable date format.

Question for @shaisachs: Some of the events have multiple times (i.e. https://events.elizabethwarren.com/event/112748/). Should we just be using the first time slot for simplicity sake and let the user discover the other times upon clicking the link to the detailed event page?

**Comment by john-osullivan** [comment]
Hey @jasonkalmeida , just got around to looking at these!  That event is crazy, good call on finding it.  Off the top of my head, we should definitely bold the location information so it stands out from whatever time info we have beneath it.

This event also highlights a bug in how I sort the times, where I only use the day of the month -- ought to make it `month-day` so that October 1st doesn't go before September 31st.  I'm working on this tonight, ought to have a PR with at least the two above points implemented before I go to bed!

As for how we present timeslots, I think your first instinct is the way to go -- it looks alright for small numbers, it just gets impossible for those big repeating events with many many days.  We can work out exactly the right numbers at which we want to collapse, but for the time being, here are the two rules I'll use:

1. If a given day has more than three slots, collapse it into something like `Thursday, Oct 17 | 5 slots from 9 AM - 5:30 PM`
2. If a given event is on more than three days, collapse the third row to just say `More Times Available from Nov 6 to Jan 2`

Some testing might show we want a different cutoff than three, we'll see how it all looks!  It'd be nice to have something about the slot length in the summaries, but since it seems to vary, I'm not sure if we can.  Once I've got something working, I'll push up a fresh PR!

**Comment by jasonkalmeida** [comment]
Closing as feature as defined has been implemented (referenced in merge request). Any future enhancements/modifications will be raised as new issues.
